/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javaLowercase;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;

import java.util.Locale;

import static javaLowercase.App.CAPITAL_ESZETT;

class AppTest {
   @ParameterizedTest
   // The challenge: Find a string and two locales that makes this test pass
   @CsvSource({
         CAPITAL_ESZETT + ",de,DE,de,CH"
   })
   void localeDependentLowercase(
         String candidate,
         String firstLang, String firstCountry,
         String secondLang, String secondCountry) {
      // See: https://www.oracle.com/java/technologies/javase/jdk8-jre8-suported-locales.html
      Assertions.assertNotEquals(
            candidate.toLowerCase(new Locale(firstLang, firstCountry)),
            candidate.toLowerCase(new Locale(secondLang, secondCountry))
      );
   }

   @ParameterizedTest
   @CsvSource({
         "i,en,US,tr,TR"
   })
   void localeDependentUppercase(
         String candidate,
         String firstLang, String firstCountry,
         String secondLang, String secondCountry) {
      // See: https://wiki.sei.cmu.edu/confluence/display/java/STR02-J.+Specify+an+appropriate+locale+when+comparing+locale-dependent+data
      Assertions.assertNotEquals(
            candidate.toUpperCase(new Locale(firstLang, firstCountry)),
            candidate.toUpperCase(new Locale(secondLang, secondCountry))
      );
   }
}
